<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="9631" started-at="2020-06-18T19:17:56 IST" finished-at="2020-06-18T19:18:05 IST">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper, io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRun.TestRunnerTestNG@a3426]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Test" duration-ms="9631" started-at="2020-06-18T19:17:56 IST" finished-at="2020-06-18T19:18:05 IST">
      <class name="testRun.TestRunnerTestNG">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:testRun.TestRunnerTestNG@a3426]" name="setUpClass" is-config="true" duration-ms="531" started-at="2020-06-18T19:17:56 IST" finished-at="2020-06-18T19:17:56 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="runScenario(io.cucumber.testng.PickleWrapper, io.cucumber.testng.FeatureWrapper)[pri:0, instance:testRun.TestRunnerTestNG@a3426]" name="runScenario" duration-ms="8944" started-at="2020-06-18T19:17:56 IST" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2020-06-18T19:18:05 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA["This is scenario"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[This is a test]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at stepDefinitions.LoginTest.loadTheURL(LoginTest.java:37)
at âœ½.load the url(file:///C:/Users/Ramesh/eclipse-workspace/OpenCart/testFeature/loginTest.feature:5)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:testRun.TestRunnerTestNG@a3426]" name="tearDownClass" is-config="true" duration-ms="93" started-at="2020-06-18T19:18:05 IST" finished-at="2020-06-18T19:18:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- testRun.TestRunnerTestNG -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
